# Generated by Django 3.2.6 on 2021-08-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbtPKID',
            fields=[
                ('Abt_PKID_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Abt_PKID_Title', models.CharField(max_length=50000)),
                ('Abt_PKID_Img', models.CharField(max_length=50000)),
                ('Abt_PKID_Des', models.CharField(max_length=99999999999999999)),
            ],
        ),
    ]
