# Generated by Django 3.2.6 on 2021-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PKID', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnPKID',
            fields=[
                ('An_PKID_Id', models.AutoField(primary_key=True, serialize=False)),
                ('An_PKID_Title', models.CharField(max_length=50000)),
                ('An_PKID_Img', models.CharField(max_length=50000)),
                ('An_PKID_Des', models.CharField(max_length=99999999999999999)),
            ],
        ),
    ]
