# Generated by Django 3.2.6 on 2021-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkUser',
            fields=[
                ('LinkUser', models.AutoField(primary_key=True, serialize=False)),
                ('LinkUserName', models.CharField(max_length=50000)),
                ('LinkUserEmail', models.CharField(max_length=50000)),
                ('LinkUserMessage', models.CharField(max_length=99999999999999999)),
            ],
        ),
    ]
