# Generated by Django 3.2.6 on 2021-08-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkuser',
            old_name='LinkUser',
            new_name='LinkUserId',
        ),
    ]
