# Generated by Django 3.2.6 on 2021-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbtPaIPC',
            fields=[
                ('Abt_Pa_IPC_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Abt_Pa_IPC_Title', models.CharField(max_length=50000)),
                ('Abt_Pa_IPC_Img', models.CharField(max_length=50000)),
                ('Abt_Pa_IPC_Des', models.CharField(max_length=99999999999999999)),
            ],
        ),
    ]
