# Generated by Django 3.2.6 on 2021-08-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('CrimesId', models.AutoField(primary_key=True, serialize=False)),
                ('CrimesName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostsId', models.AutoField(primary_key=True, serialize=False)),
                ('PostsTitle', models.CharField(max_length=100)),
                ('PostsDescription', models.CharField(max_length=8000)),
                ('Crime', models.CharField(max_length=500)),
                ('CrimeDate', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
