# Generated by Django 3.2.6 on 2021-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DwChild', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnDwChild',
            fields=[
                ('An_Dw_Child_Id', models.AutoField(primary_key=True, serialize=False)),
                ('An_Dw_Child_Title', models.CharField(max_length=50000)),
                ('An_Dw_Child_Img', models.CharField(max_length=50000)),
                ('An_Dw_Child_Des', models.CharField(max_length=99999999999999999)),
            ],
        ),
    ]
