# Generated by Django 3.2.6 on 2021-08-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DwW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnDwW',
            fields=[
                ('An_Dw_W_Id', models.AutoField(primary_key=True, serialize=False)),
                ('An_Dw_W_Title', models.CharField(max_length=50000)),
                ('An_Dw_W_Img', models.CharField(max_length=50000)),
                ('An_Dw_W_Des', models.CharField(max_length=99999999999999999)),
            ],
        ),
    ]
