# Generated by Django 3.2.6 on 2021-08-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='AboutInfo',
            field=models.CharField(max_length=999999999999999),
        ),
    ]
