# Generated by Django 3.2.6 on 2021-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0002_alter_about_aboutinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBg',
            fields=[
                ('AboutBgId', models.AutoField(primary_key=True, serialize=False)),
                ('AboutBgPhoto', models.CharField(max_length=100)),
            ],
        ),
    ]
