# Generated by Django 3.2.4 on 2021-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vission',
            fields=[
                ('VissionId', models.AutoField(primary_key=True, serialize=False)),
                ('VissionInfo', models.CharField(max_length=5000)),
            ],
        ),
    ]
