# Generated by Django 3.2.6 on 2021-08-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DwSC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnDwSC',
            fields=[
                ('An_Dw_SC_Id', models.AutoField(primary_key=True, serialize=False)),
                ('An_Dw_SC_Title', models.CharField(max_length=50000)),
                ('An_Dw_SC_Img', models.CharField(max_length=50000)),
                ('An_Dw_SC_Des', models.CharField(max_length=99999999999999999)),
            ],
        ),
    ]
