# Generated by Django 3.2.6 on 2021-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaSLL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnPaSLL',
            fields=[
                ('An_Pa_SLL_Id', models.AutoField(primary_key=True, serialize=False)),
                ('An_Pa_SLL_Title', models.CharField(max_length=50000)),
                ('An_Pa_SLL_Img', models.CharField(max_length=50000)),
                ('An_Pa_SLL_Des', models.CharField(max_length=99999999999999999)),
            ],
        ),
    ]
